name: 'Setup Node, deno, pnpm & install'

description: 'Setup node, deno, pnpm and install'

runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v4.0.0
      with:
        version: 8

    - uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'pnpm'
        cache-dependency-path: './pnpm-lock.yaml'

    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x

    - name: Install
      shell: bash
      run: pnpm install --frozen-lockfile

